name: Scrape and Rewrite News
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

# Añade esto:
permissions:
  contents: write  # Permite hacer push al repositorio

jobs:
  scrape-and-rewrite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Token automático de GitHub
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install beautifulsoup4 requests
      - name: Run scraper
        run: python scraper.py
      - name: Rewrite news with AI
        run: python rewrite.py
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add noticias.txt noticias_reescritas.txt
          git commit -m "Update news: $(date)"
          git push
